version: '3.5' 
 
volumes: 
  jupyter: 
    driver: local 
 
services: 
  jupyter: 
    image: jupyter/datascience-notebook:julia-1.9.1
    ports: 
      - 8888:8888 
    volumes: 
     - ./:/home/jovyan/work 
    environment: 
     - JUPYTER_ENABLE_LAB=yes 
    command: start-notebook.sh --NotebookApp.token='supersave_token' --no-browser --allow-root --notebook-dir=/home/jovyan/work 